<script type="module">
  // Import the functions you need from the SDKs you need
  import { initializeApp } from "https://www.gstatic.com/firebasejs/12.9.0/firebase-app.js";
  // TODO: Add SDKs for Firebase products that you want to use
  // https://firebase.google.com/docs/web/setup#available-libraries

  // Your web app's Firebase configuration
  const firebaseConfig = {
    apiKey: "AIzaSyDA67oWl6Kq1kNXLylumXlC7YV5tgrsnBs",
    authDomain: "central-public-school-1cd53.firebaseapp.com",
    projectId: "central-public-school-1cd53",
    storageBucket: "central-public-school-1cd53.firebasestorage.app",
    messagingSenderId: "490014133859",
    appId: "1:490014133859:web:f89fe318d46e3e768c3256"
  };

  // Initialize Firebase
  const app = initializeApp(firebaseConfig);
</script>